### ISSUE TITLE
Variables Environnement 

### ISSUE THREAD

**Issue by tototidan** [Tronix117/wik-devops-3tp#3]
Sur mon docker compose , je passe les variables d'environnement de cette façon : 

```version: '2.1'
services:
  homecolis:
    image: homecolis-api:latest
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_HOST=db-mongo
      - MONGO_DATABASE=admin
      - MONGO_USER=someadmin
      - MONGO-PASSWORD=secret
```

C'est un exemple sans mongo , mais dés que je lance le up , j'ai une erreur du container api qui me dit que les variables ne sont pas "set". Du coup pour tester , j'ai fait un console.log de process.env. Et je vois bien dans la liste qu'il m'affiche toutes mes variables ( sauf une bizarrement ) dans la liste mais qu'il n'arrive pas a les lire dés que j'essaye de les attribuer a une variable ! donc je tombe dans le cas du premier IF qui vérifie si les valeurs sont bien set ou non et ça passe pas ! 

Une solution ou une piste de solutions peut-être ?

**Comment by Tronix117** [comment]
Relis-toi ;)

**Comment by tototidan** [comment]
Avec exactement le même code mais une version plus récentes de docker compose ça marche ! (j'avais oublié de copier coller le version en haut de mon docker compose mais il était bien présent )

**Comment by Tronix117** [comment]
N’empeche, tu as quand même une erreur sur la dernière ligne !!

**Comment by tototidan** [comment]
Oui en effet ! Mais même sans ça , docker avait un comportement bizarre , j'avais une version trop ancienne je pense
