### ISSUE TITLE
[Question] Mongo master

### ISSUE THREAD

**Issue by AerWyn81** [Tronix117/wik-devops-3tp#4]
Bonjour,

Je voulais juste savoir si le résultat attendu pour le screenshot 2-a-2 sur le navigateur avec l'ip du mongo-master est bien celui-ci : 

![image](https://user-images.githubusercontent.com/22222045/34381779-f3290e28-eb0a-11e7-946b-12f5e35496ac.png)

![image](https://user-images.githubusercontent.com/22222045/34381767-e271d1a0-eb0a-11e7-9f4f-295bcd33d650.png)

Cordialement,
Vincent

**Comment by Tronix117** [comment]
Non, tu dois faire un screenshot de l'API sur l'url `/mongo`, donc si tu as bindé l'API sur le port 8080, ça devrait plus être `http://127.0.0.1:8080/mongo`.

**Comment by Tronix117** [comment]
Ce que j'attends ici, c'est que tu lances l'API en local avec en variables d'environnement les infos de connexion au serveur mongo qui est sur la machine distante. Et donc que tu prennes un screenshot du `http://127.0.0.1:8080/mongo` (si tu as bindé l'API sur le port `8080`).

(Ne pas oublier de débloquer le port 27017 sur AWS)

**Comment by AerWyn81** [comment]
Effectivement, je pense que j'ai réussi à lancer mongodb sur le serveur master et pas dans un container, d'où le fait que j'accède à quelque chose avec le port 27017 direct depuis l'ip... 

Moi qui espérait avoir trouvé quelque chose, quelle déception !

Pour les ports, c'est ok j'y avais pensé!

**Comment by Tronix117** [comment]
Ben en soit ça a l'air bon ton provisionning, car mongo a l'air installé sur le serveur (c'est un message du serveur mongo que tu as).

Maintenant, il faut juste tester de s'y connecter et me donner la preuve que tu arrives à t'y connecter. Un simple lancement de l'API avec `docker run` avec les bon `-e` d'environnement me va pour faire le screenshot

**Comment by AerWyn81** [comment]
Ah oui d'accord je comprends, enfait c'est pas l'ip du serveur mongo master qui va me dire si la liaison est bonne (lui va juste me dire si mongo est bien installé/démarré), c'est sur l'ip de mon docker, c'est lui qui va me dire si la liaison avec le mongo master est bonne. Okkkk.

Pour le coup j'ai une erreur d'authentification, le lien fonctionne, pourtant mon `docker-compose.yml`  et `group_vars/all.yml` ont les mêmes user/pass/database_name, c'est bien dans `group_vars/all.yml` que je créer les identifiants de la base de données et dans le `docker-compose.yml`  que je défini ces mêmes valeurs pour qu'il réussisse à se connecter ?

**Comment by Tronix117** [comment]
Je dirai plus quelque chose comme `group_vars/mongo.yml`
C'est le cas.

Par contre pour faire ce test, n'oublie pas de mettre l'ip du serveur distant dans le MONGO_HOST de l'API

**Comment by AerWyn81** [comment]
Ok j'ai réussi ! Merci !

Cordialement,
Vincent
